language: java
install: true
jdk: oraclejdk11

script:
  - chmod +x gradlew
  - export SKIP_GUI=True
  - ./gradlew build
  - ./gradlew test
  - ./gradlew checkstyleMain
  - ./gradlew checkstyleTest

after_success:
  - bash <(curl -s https://codecov.io/bash)
