language: java
install: true
jdk: oraclejdk8

services:
  - xvfb

script:
  - chmod +x gradlew
  - export SKIP_GUI=True
  - ./gradlew build
  - ./gradlew test
  - ./gradlew checkstyleMain
  - ./gradlew checkstyleTest
